#!/bin/sh -e
#
# runs all the components of lighting control
# pathname should be added to /etc/rc.local to autorun on pi
#
# alias python=python3

#python /home/pi/dev/labyrinth/cmdqmanager.py &

#only need runflask as of 9/9/2016
/home/pi/dev/labyrinth/runflask &


#python /home/pi/dev/labyrinth/laby.py &

